### ISSUE TITLE
403 response from pypi on get_current_or_latest_version()

### ISSUE THREAD

**Issue by pleasedontbelong** [ewjoachim/raincoat#25]
I got a 403 response from pypi because raincoat is not calling with https [here](https://github.com/ewjoachim/raincoat/blob/master/raincoat/source.py#L83)

### source.py
```
    pypi_url = "http://pypi.python.org/pypi/{}/json".format(package)
    releases = requests.get(pypi_url).json()["releases"]
```

we should also add an assert on the response code. The error message from the traceback was not helpful XD :
`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by ewjoachim** [comment]
Hello ! Thanks for your issue and thanks a lot for contributing!

It seems that you analysis is correct! I'll issue a new release as soon as we merge this.
