### ISSUE TITLE
KeyError: 'raincoat.match'

### ISSUE THREAD

**Issue by sampaccoud** [ewjoachim/raincoat#32]
This error appeared on our builds with no apparent change:
https://app.circleci.com/pipelines/github/openfun/fun-richie-site-factory/98/workflows/4d0b471c-1761-4b78-889c-d2cbd88fe795/jobs/2619

```python
>>> [ep.name for ep in importlib_metadata.entry_points() if "raincoat" in ep.name]
['raincoat']
```

Do you see any reason for the "raincoat.match" entrypoint declaration to be ignored in [setup.cfg](https://github.com/ewjoachim/raincoat/blob/master/setup.cfg#L74)? :thinking:

**Comment by ewjoachim** [comment]
Hey :)

I haven't been... very seriously maintaining this lib through the years... 😅

Seems like you're using it, would you be interested in taking a part in the maintenance ? I'm sure that if there's some activity, it will be much easier for me to spend time polishing it :)

No idea where that might come from. New release of importlib-metadata ?

**Comment by ewjoachim** [comment]
I'll be delighted. I'll try to spend some time working on it in the next few days :)

**Comment by ewjoachim** [comment]
Keeping it open until I manage to issue a release but that should happen quicky

**Comment by ewjoachim** [comment]
https://pypi.org/project/raincoat/1.2.4/ 🎉
